### PR TITLE
Duplicate CCID/Accounts Fix. Closes #693.

### LINKED ISSUE #693: CCID Linking still resulted in Duplicate Users
Sharon & Sonya were able to link their existing accounts to their CCIDs (confirmed via console that ccid and provider were set on the old accounts), but the CCID account was not cleaned up during the link, and consequently when they logged in they ended up in the new account, which did not own any files.

Sharon reported a redirect loop that may be related:

"i was able to associate my account with ccid but when i log in it wants me to go through the steps again. and even if i confirm my email it won't let me go anywhere else in new era. i've got myself on a loop"

There exists some path through the email confirmation that is failing to clean up the temporary ccid-only account. Ideally, would like to refactor this to eliminate the temporary ccid account created before the linking workflow. It's a rich source of bugs for little gain.

### PR DESCRIPTION
**Pull request by mbarnett**
Cleans up confirmation logic, makes shibboleth work across TestShib and IST providers, normalizes TestShib responses to match those sent by IST, makes tests consistent with IST responses, and fixes an issue with duplicate users being created in some scenarios.

### CODE REVIEW

File: app/models/user.rb [hunk 1]
```diff
@@ -69,7 +71,7 @@ def link_pending?
   end
 
   def link!(other_account)
-    self.ccid = other_account.email
+    self.ccid = other_account.ccid
```
Comment (mbarnett) [inline app/models/user.rb]: For those wondering, this was the entire actual bug.

**Comment by pbinkley** [comment]
My specs are still running...

**Comment by pbinkley** [comment]
... and argh! now I'm starting to see some F's.

**Comment by mbarnett** [comment]
You'll see at least the random migration failures on this branch.

We really need to speed up the spec suite in general.

**Comment by pbinkley** [comment]
After all that I'm getting user-related errors e.g.:

```
 15) coauthor abby shares work @ included
      Failure/Error: sign_in abby
        expected not to find text "Invalid email or password." in "education & research archive ERA Search ERA Login home browse search upload your research contact × Invalid email or password. Login to ERA ERA is now a CCID (Campus Computing ID) enabled service. If you have a CCID please use it to log in to ERA. If you have an existing ERA account, it will be linked to your CCID the first time you log in. Do you have a University of Alberta CCID (Campus Computing ID)? YES, I have a CCID NO, I do not have a CCID Quick Links Login Browse Search Share Your Research Policies Content Policy Mediated Deposit Metadata Policy Get Help Contact Us © University of Alberta Libraries | University of Alberta, Edmonton, AB, Canada T6G 2R3 | Web Site Privacy Policy"
      # ./spec/spec_helper.rb:153:in `sign_in'
      # ./spec/features/coauthor_spec.rb:24:in `block (3 levels) in <top (required)>'
```

**Comment by pbinkley** [comment]
Tests pass when run in right environment.
