### PR TITLE
686 failing specs

### LINKED ISSUE #686: Failing specs in master branch
Failures:

  1) RedirectController#datastream Item should be migrated
     Failure/Error: expect(subject.fedora3uuid).to eq "uuid:394266f0-0e4a-42e6-a199-158165226426"

       expected: "uuid:394266f0-0e4a-42e6-a199-158165226426"
            got: nil

       (compared using ==)
     # ./spec/controllers/redirect_controller_spec.rb:67:in `block (3 levels) in <top (required)>'

  3) generic file new new item fields should not allow multiple resource_type selections, but assign to an array
     Failure/Error: expect(page).to have_xpath('//select[@name="generic_file[resource_type][]" and not(@multiple)]')
       expected to find xpath "//select[@name=\"generic_file[resource_type][]\" and not(@multiple)]" but there were no matches
     # ./spec/forms/generic_file_new_form_spec.rb:39:in `block (3 levels) in <top (required)>'

  4) Migration rake tasks migration:dataverse dataverse item should be migrated
     Failure/Error: expect(subject.remote_resource).to eq "dataverse"

       expected: "dataverse"
            got: nil

       (compared using ==)
     # ./spec/tasks/dataverse_migration_rake_spec.rb:28:in `block (3 levels) in <top (required)>'

Finished in 23 minutes 10 seconds (files took 51.19 seconds to load)
328 examples, 4 failures

### PR DESCRIPTION
**Pull request by pgwillia**
* remove collection_perf_spec.rb
  * because it was disabled
  * because it messes with features sign_in
* modify selects_collection_spec.rb setup because it messes with features sign in (looking for feedback!)
* fix "Is in" community display
* only run specs once

fixes #686

### CODE REVIEW

File: spec/controllers/selects_collections_spec.rb [hunk 1]
```diff
@@ -7,28 +7,27 @@ class SelectsCollectionsController < ApplicationController
 end
 
 describe SelectsCollectionsController, :type => :controller do
+  let(:user) { FactoryGirl.find_or_create(:jill) }
+  let(:dit) { FactoryGirl.find_or_create(:dit) }
   describe "Select Communities" do
-    before :all do
+    before :each do
```
Comment (weiweishi) [inline spec/controllers/selects_collections_spec.rb]: why the community/collection need to be set up for each test? Can we reuse them for all the tests in this spec?

Comment (pgwillia) [inline spec/controllers/selects_collections_spec.rb]: I did some experimenting with this and used let statements for everything
that is set up in the before block.  The result:
```
1) SelectsCollectionsController Select Communities Public Access should
return public communities
     Failure/Error: expect(assigns[:user_communities].map(&:id)).to
match_array [community.id, no_edit_community.id]
       expected collection contained:  ["9z902z939", "cv43nw87f"]
       actual collection contained:    []
       the missing elements were:      ["9z902z939", "cv43nw87f"]
     # ./spec/controllers/selects_collections_spec.rb:49:in `block (4
levels) in <top (required)>'

  2) SelectsCollectionsController Select Communities Public Access should
not return public collections
     Failure/Error: expect(assigns[:user_communities].map(&:id)).not_to
include @collection.id
     NoMethodError:
       undefined method `id' for nil:NilClass
     # ./spec/controllers/selects_collections_spec.rb:53:in `block (4
levels) in <top (required)>'

  3) SelectsCollectionsController Select Communities Regular User Read
Access signed in should return only public and read access (edit access
implies read) communities
     Failure/Error: expect(assigns[:user_communities].map(&:id)).to
match_array [community.id, no_edit_community.id]
       expected collection contained:  ["8049g5125", "rx913p93b"]
       actual collection contained:    ["9z902z939", "cv43nw87f"]
       the missing elements were:      ["8049g5125", "rx913p93b"]
       the extra elements were:        ["9z902z939", "cv43nw87f"]
     # ./spec/controllers/selects_collections_spec.rb:68:in `block (5
levels) in <top (required)>'

  4) SelectsCollectionsController Select Communities Regular User Edit
Access signed in should return only public or editable communities
     Failure/Error: expect(assigns[:user_communities].map(&:id)).to
match_array [community.id]
       expected collection contained:  ["qn59q402s"]
       actual collection contained:    ["9z902z939", "rx913p93b"]
       the missing elements were:      ["qn59q402s"]
       the extra elements were:        ["9z902z939", "rx913p93b"]
     # ./spec/controllers/selects_collections_spec.rb:85:in `block (5
levels) in <top (required)>'
```

I suppose it's lazy but I decided to go back to what worked.

Comment (pgwillia) [inline spec/controllers/selects_collections_spec.rb]: * there is likely a better approach to this
 * consider function and better placement of Collection.delete_all
 * do not use before :each

**Comment by weiweishi** [comment]
9 failures now with this PR:
 1) delete admin can delete
     Failure/Error: expect(page).to have_content( "The file has been deleted." )
       expected to find text "The file has been deleted." in "ActionController::InvalidAuthenticityToken at /files/ms35t8816 ============================================================== > ActionController::InvalidAuthenticityToken spec/features/admin_delete_spec.rb, line 63 ------------------------------------------- ``` ruby 58 end 59 60 def select_delete(file) 61 within(\"#document_\#{file.id}\") do 62 click_button \"Select an action\" > 63 click_link \"Delete File\" 64 end 65 end 66 67 def create_batch(file) 68 within(\"#document_\#{file.id}\") do ``` App backtrace ------------- - spec/features/admin_delete_spec.rb:63:in `block in select_delete' - spec/features/admin_delete_spec.rb:61:in `select_delete' - spec/features/admin_delete_spec.rb:21:in `block (3 levels) in ' Full backtrace -------------- - actionpack (4.2.3) lib/action_controller/metal/request_forgery_protection.rb:181:in `handle_unverified_request' - actionpack (4.2.3) lib/action_controller/metal/request_forgery_protection.rb:209:in `handle_unverified_request' - devise (3.5.2) lib/devise/controllers/helpers.rb:251:in `handle_unverified_request' - actionpack (4.2.3) lib/action_controller/metal/request_forgery_protection.rb:204:in `verify_authenticity_token' - activesupport (4.2.3) lib/active_support/callbacks.rb:430:in `block in make_lambda' - activesupport (4.2.3) lib/active_support/callbacks.rb:162:in `block in halting' - activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `block in call' - activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call' - activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks' - actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action' - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument' - activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument' - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument' - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action' - activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action' - actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process' - actionview (4.2.3) lib/action_view/rendering.rb:30:in `process' - actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch' - actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch' - actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve' - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve' - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call' - railties (4.2.3) lib/rails/engine.rb:518:in `call' - railties (4.2.3) lib/rails/railtie.rb:194:in `method_missing' - actionpack (4.2.3) lib/action_dispatch/routing/mapper.rb:51:in `serve' - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve' - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call' - omniauth (1.2.2) lib/omniauth/strategy.rb:186:in `call!' - omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call' - warden (1.2.3) lib/warden/manager.rb:35:in `block in call' - warden (1.2.3) lib/warden/manager.rb:34:in `call' - rack (1.6.4) lib/rack/etag.rb:24:in `call' - rack (1.6.4) lib/rack/conditionalget.rb:38:in `call' - rack (1.6.4) lib/rack/head.rb:13:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call' - rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context' - rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call' - activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call' - active-fedora (9.4.2) lib/active_fedora/ldp_cache.rb:26:in `call' - activerecord (4.2.3) lib/active_record/migration.rb:377:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call' - activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks' - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call' - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call' - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call' - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' - railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app' - railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call' - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged' - activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged' - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged' - railties (4.2.3) lib/rails/rack/logger.rb:20:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call' - rack (1.6.4) lib/rack/methodoverride.rb:22:in `call' - rack (1.6.4) lib/rack/runtime.rb:18:in `call' - activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' - rack (1.6.4) lib/rack/lock.rb:17:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call' - rack (1.6.4) lib/rack/sendfile.rb:113:in `call' - railties (4.2.3) lib/rails/engine.rb:518:in `call' - railties (4.2.3) lib/rails/application.rb:165:in `call' - rack (1.6.4) lib/rack/urlmap.rb:66:in `block in call' - rack (1.6.4) lib/rack/urlmap.rb:50:in `call' - rack-test (0.6.3) lib/rack/mock_session.rb:30:in `request' - rack-test (0.6.3) lib/rack/test.rb:244:in `process_request' - rack-test (0.6.3) lib/rack/test.rb:94:in `delete' - /usr/lib64/ruby/2.1.0/forwardable.rb:183:in `delete' - capybara (2.5.0) lib/capybara/rack_test/browser.rb:60:in `process' - capybara (2.5.0) lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects' - capybara (2.5.0) lib/capybara/rack_test/browser.rb:31:in `follow' - capybara (2.5.0) lib/capybara/rack_test/node.rb:57:in `click' - capybara (2.5.0) lib/capybara/node/element.rb:134:in `block in click' - capybara (2.5.0) lib/capybara/node/base.rb:84:in `synchronize' - capybara (2.5.0) lib/capybara/node/element.rb:134:in `click' - capybara (2.5.0) lib/capybara/node/actions.rb:26:in `click_link' - capybara (2.5.0) lib/capybara/session.rb:698:in `block (2 levels) in ' - capybara (2.5.0) lib/capybara/dsl.rb:51:in `block (2 levels) in ' - spec/features/admin_delete_spec.rb:63:in `block in select_delete' - capybara (2.5.0) lib/capybara/session.rb:290:in `within' - capybara (2.5.0) lib/capybara/dsl.rb:51:in `block (2 levels) in ' - spec/features/admin_delete_spec.rb:61:in `select_delete' - spec/features/admin_delete_spec.rb:21:in `block (3 levels) in ' - rspec-core (3.3.2) lib/rspec/core/example.rb:206:in `block in run' - rspec-core (3.3.2) lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks' - rspec-core (3.3.2) lib/rspec/core/example.rb:388:in `block in with_around_example_hooks' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:478:in `block in run' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for' - rspec-core (3.3.2) lib/rspec/core/example.rb:273:in `call' - rspec-rails (3.3.3) lib/rspec/rails/adapters.rb:127:in `block (2 levels) in ' - rspec-core (3.3.2) lib/rspec/core/example.rb:378:in `instance_exec' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:389:in `execute_with' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for' - rspec-core (3.3.2) lib/rspec/core/example.rb:273:in `call' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:478:in `run' - rspec-core (3.3.2) lib/rspec/core/example.rb:388:in `with_around_example_hooks' - rspec-core (3.3.2) lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks' - rspec-core (3.3.2) lib/rspec/core/example.rb:203:in `run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:559:in `block in run_examples' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:555:in `run_examples' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:521:in `run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `block in run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `run' - rspec-core (3.3.2) lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs' - rspec-core (3.3.2) lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs' - rspec-core (3.3.2) lib/rspec/core/configuration.rb:1627:in `with_suite_hooks' - rspec-core (3.3.2) lib/rspec/core/runner.rb:114:in `block in run_specs' - rspec-core (3.3.2) lib/rspec/core/reporter.rb:77:in `report' - rspec-core (3.3.2) lib/rspec/core/runner.rb:113:in `run_specs' - rspec-core (3.3.2) lib/rspec/core/runner.rb:89:in `run' - rspec-core (3.3.2) lib/rspec/core/runner.rb:73:in `run' - rspec-core (3.3.2) lib/rspec/core/runner.rb:41:in `invoke' - rspec-core (3.3.2) exe/rspec:4:in `' - /usr/bin/rspec:23:in `'"
     # ./spec/features/admin_delete_spec.rb:22:in `block (3 levels) in <top (required)>'

  2) Rights check if rights does exist should not text "Invalid email or password."
     Failure/Error: click_button "Update Generic file"
     Capybara::ElementNotFound:
       Unable to find button "Update Generic file"
     # ./spec/features/edit_rights_spec.rb:47:in `block (3 levels) in <top (required)>'

  3) SAML Users with existing legacy accounts whose CCID and legacy address are identical should automatically be associated with their CCID when logging in using it
     Failure/Error: User.destroy_all
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Table 'hydranorthdev.bookmarks' doesn't exist: SHOW FULL FIELDS FROM `bookmarks`
     # ./spec/features/saml_spec.rb:43:in `block (3 levels) in <top (required)>'

  4) SAML Users with existing legacy accounts logging in via SAML for the first time should receive an email confirmation to link to their existing account
     Got 1 failure and 1 other error:

     4.1) Failure/Error: expect(page).to have_content I18n.t('devise.confirmations.send_paranoid_instructions')
            expected to find text "If your email address exists in our database, you will receive an email with instructions for how to confirm your email address in a few minutes." in "Mysql2::Error at /users/myself@ualberta-dot-ca/set_saml ======================================================= > Table 'hydranorthdev.bookmarks' doesn't exist app/controllers/users_controller.rb, line 47 -------------------------------------------- ``` ruby 42 43 if pending 44 flash[:notice] = I18n.t('devise.confirmations.send_paranoid_instructions', :kind => 'Shibboleth') 45 sign_out @user 46 # delete the extraneous CCID account > 47 @user.destroy 48 else 49 flash[:notice] = I18n.t('devise.omniauth_callbacks.success', :kind => 'Shibboleth') 50 sign_in_and_redirect @user, :event => :authentication 51 end 52 end ``` App backtrace ------------- - app/controllers/users_controller.rb:47:in `set_saml' - spec/features/saml_spec.rb:71:in `block (5 levels) in ' - spec/features/saml_spec.rb:71:in `block (4 levels) in ' Full backtrace -------------- - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log' - activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute' - activerecord (4.2.3) lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:312:in `execute_and_free' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:457:in `columns' - activerecord (4.2.3) lib/active_record/connection_adapters/schema_cache.rb:43:in `columns' - activerecord (4.2.3) lib/active_record/connection_adapters/schema_cache.rb:49:in `columns_hash' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:85:in `column_for' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:94:in `bind' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:103:in `last_chain_scope' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:139:in `add_constraints' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:39:in `scope' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:5:in `scope' - activerecord (4.2.3) lib/active_record/associations/association.rb:97:in `association_scope' - activerecord (4.2.3) lib/active_record/associations/association.rb:86:in `scope' - activerecord (4.2.3) lib/active_record/associations/collection_association.rb:423:in `scope' - activerecord (4.2.3) lib/active_record/associations/collection_association.rb:435:in `get_records' - activerecord (4.2.3) lib/active_record/associations/collection_association.rb:455:in `find_target' - activerecord (4.2.3) lib/active_record/associations/collection_association.rb:392:in `load_target' - activerecord (4.2.3) lib/active_record/associations/has_many_association.rb:26:in `handle_dependency' - activerecord (4.2.3) lib/active_record/associations/builder/association.rb:146:in `block in add_destroy_callbacks' - activesupport (4.2.3) lib/active_support/callbacks.rb:446:in `block in make_lambda' - activesupport (4.2.3) lib/active_support/callbacks.rb:162:in `block in halting' - activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `block in call' - activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call' - activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks' - activerecord (4.2.3) lib/active_record/callbacks.rb:292:in `destroy' - activerecord (4.2.3) lib/active_record/transactions.rb:281:in `block in destroy' - activerecord (4.2.3) lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction' - activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction' - activerecord (4.2.3) lib/active_record/transactions.rb:348:in `with_transaction_returning_status' - activerecord (4.2.3) lib/active_record/transactions.rb:281:in `destroy' - app/controllers/users_controller.rb:47:in `set_saml' - actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action' - actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action' - actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action' - activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call' - activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile' - activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call' - activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks' - actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action' - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument' - activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument' - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument' - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action' - activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action' - actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process' - actionview (4.2.3) lib/action_view/rendering.rb:30:in `process' - actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch' - actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch' - actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve' - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve' - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call' - omniauth (1.2.2) lib/omniauth/strategy.rb:404:in `call_app!' - omniauth (1.2.2) lib/omniauth/strategy.rb:262:in `mock_call!' - omniauth (1.2.2) lib/omniauth/strategy.rb:181:in `call!' - omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call' - warden (1.2.3) lib/warden/manager.rb:35:in `block in call' - warden (1.2.3) lib/warden/manager.rb:34:in `call' - rack (1.6.4) lib/rack/etag.rb:24:in `call' - rack (1.6.4) lib/rack/conditionalget.rb:25:in `call' - rack (1.6.4) lib/rack/head.rb:13:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call' - rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context' - rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call' - activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call' - active-fedora (9.4.2) lib/active_fedora/ldp_cache.rb:26:in `call' - activerecord (4.2.3) lib/active_record/migration.rb:377:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call' - activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks' - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call' - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call' - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call' - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' - railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app' - railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call' - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged' - activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged' - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged' - railties (4.2.3) lib/rails/rack/logger.rb:20:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call' - rack (1.6.4) lib/rack/methodoverride.rb:22:in `call' - rack (1.6.4) lib/rack/runtime.rb:18:in `call' - activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' - rack (1.6.4) lib/rack/lock.rb:17:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call' - rack (1.6.4) lib/rack/sendfile.rb:113:in `call' - railties (4.2.3) lib/rails/engine.rb:518:in `call' - railties (4.2.3) lib/rails/application.rb:165:in `call' - rack (1.6.4) lib/rack/urlmap.rb:66:in `block in call' - rack (1.6.4) lib/rack/urlmap.rb:50:in `call' - rack-test (0.6.3) lib/rack/mock_session.rb:30:in `request' - rack-test (0.6.3) lib/rack/test.rb:244:in `process_request' - rack-test (0.6.3) lib/rack/test.rb:58:in `get' - /usr/lib64/ruby/2.1.0/forwardable.rb:183:in `get' - capybara (2.5.0) lib/capybara/rack_test/browser.rb:60:in `process' - capybara (2.5.0) lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects' - capybara (2.5.0) lib/capybara/rack_test/browser.rb:26:in `submit' - capybara (2.5.0) lib/capybara/rack_test/form.rb:76:in `submit' - capybara (2.5.0) lib/capybara/rack_test/node.rb:61:in `click' - capybara (2.5.0) lib/capybara/node/element.rb:134:in `block in click' - capybara (2.5.0) lib/capybara/node/base.rb:84:in `synchronize' - capybara (2.5.0) lib/capybara/node/element.rb:134:in `click' - capybara (2.5.0) lib/capybara/node/actions.rb:39:in `click_button' - capybara (2.5.0) lib/capybara/session.rb:698:in `block (2 levels) in ' - capybara (2.5.0) lib/capybara/dsl.rb:51:in `block (2 levels) in ' - spec/features/saml_spec.rb:71:in `block (5 levels) in ' - rspec-expectations (3.3.1) lib/rspec/matchers/built_in/raise_error.rb:49:in `matches?' - rspec-expectations (3.3.1) lib/rspec/matchers/built_in/raise_error.rb:67:in `does_not_match?' - rspec-expectations (3.3.1) lib/rspec/expectations/handler.rb:78:in `does_not_match?' - rspec-expectations (3.3.1) lib/rspec/expectations/handler.rb:72:in `block in handle_matcher' - rspec-expectations (3.3.1) lib/rspec/expectations/handler.rb:27:in `with_matcher' - rspec-expectations (3.3.1) lib/rspec/expectations/handler.rb:70:in `handle_matcher' - rspec-expectations (3.3.1) lib/rspec/expectations/expectation_target.rb:67:in `not_to' - rspec-expectations (3.3.1) lib/rspec/expectations/expectation_target.rb:92:in `not_to' - spec/features/saml_spec.rb:71:in `block (4 levels) in ' - rspec-core (3.3.2) lib/rspec/core/example.rb:206:in `block in run' - rspec-core (3.3.2) lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks' - rspec-core (3.3.2) lib/rspec/core/example.rb:388:in `block in with_around_example_hooks' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:478:in `block in run' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for' - rspec-core (3.3.2) lib/rspec/core/example.rb:273:in `call' - rspec-rails (3.3.3) lib/rspec/rails/adapters.rb:127:in `block (2 levels) in ' - rspec-core (3.3.2) lib/rspec/core/example.rb:378:in `instance_exec' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:389:in `execute_with' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for' - rspec-core (3.3.2) lib/rspec/core/example.rb:273:in `call' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:478:in `run' - rspec-core (3.3.2) lib/rspec/core/example.rb:388:in `with_around_example_hooks' - rspec-core (3.3.2) lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks' - rspec-core (3.3.2) lib/rspec/core/example.rb:203:in `run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:559:in `block in run_examples' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:555:in `run_examples' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:521:in `run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `block in run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `block in run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `run' - rspec-core (3.3.2) lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs' - rspec-core (3.3.2) lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs' - rspec-core (3.3.2) lib/rspec/core/configuration.rb:1627:in `with_suite_hooks' - rspec-core (3.3.2) lib/rspec/core/runner.rb:114:in `block in run_specs' - rspec-core (3.3.2) lib/rspec/core/reporter.rb:77:in `report' - rspec-core (3.3.2) lib/rspec/core/runner.rb:113:in `run_specs' - rspec-core (3.3.2) lib/rspec/core/runner.rb:89:in `run' - rspec-core (3.3.2) lib/rspec/core/runner.rb:73:in `run' - rspec-core (3.3.2) lib/rspec/core/runner.rb:41:in `invoke' - rspec-core (3.3.2) exe/rspec:4:in `' - /usr/bin/rspec:23:in `'"
          # ./spec/features/saml_spec.rb:72:in `block (4 levels) in <top (required)>'

     4.2) Failure/Error: User.destroy_all
          ActiveRecord::StatementInvalid:
            Mysql2::Error: Table 'hydranorthdev.bookmarks' doesn't exist: SHOW FULL FIELDS FROM `bookmarks`
          # ./spec/features/saml_spec.rb:43:in `block (3 levels) in <top (required)>'

  5) SAML Users with existing legacy accounts logging in via SAML for the first time should not be able to step out of the linking workflow
     Failure/Error: User.destroy_all
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Table 'hydranorthdev.bookmarks' doesn't exist: SHOW FULL FIELDS FROM `bookmarks`
     # ./spec/features/saml_spec.rb:43:in `block (3 levels) in <top (required)>'

  6) SAML Users with existing legacy accounts logging in via SAML for the first time should not be able to enumerate user accounts via the linking workflow
     Got 1 failure and 1 other error:

     6.1) Failure/Error: expect(page).to have_content I18n.t('devise.confirmations.send_paranoid_instructions')
            expected to find text "If your email address exists in our database, you will receive an email with instructions for how to confirm your email address in a few minutes." in "Mysql2::Error at /users/myself@ualberta-dot-ca/set_saml ======================================================= > Table 'hydranorthdev.bookmarks' doesn't exist app/controllers/users_controller.rb, line 47 -------------------------------------------- ``` ruby 42 43 if pending 44 flash[:notice] = I18n.t('devise.confirmations.send_paranoid_instructions', :kind => 'Shibboleth') 45 sign_out @user 46 # delete the extraneous CCID account > 47 @user.destroy 48 else 49 flash[:notice] = I18n.t('devise.omniauth_callbacks.success', :kind => 'Shibboleth') 50 sign_in_and_redirect @user, :event => :authentication 51 end 52 end ``` App backtrace ------------- - app/controllers/users_controller.rb:47:in `set_saml' - spec/features/saml_spec.rb:105:in `block (5 levels) in ' - spec/features/saml_spec.rb:105:in `block (4 levels) in ' Full backtrace -------------- - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log' - activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `execute' - activerecord (4.2.3) lib/active_record/connection_adapters/mysql2_adapter.rb:231:in `execute' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:312:in `execute_and_free' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract_mysql_adapter.rb:457:in `columns' - activerecord (4.2.3) lib/active_record/connection_adapters/schema_cache.rb:43:in `columns' - activerecord (4.2.3) lib/active_record/connection_adapters/schema_cache.rb:49:in `columns_hash' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:85:in `column_for' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:94:in `bind' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:103:in `last_chain_scope' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:139:in `add_constraints' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:39:in `scope' - activerecord (4.2.3) lib/active_record/associations/association_scope.rb:5:in `scope' - activerecord (4.2.3) lib/active_record/associations/association.rb:97:in `association_scope' - activerecord (4.2.3) lib/active_record/associations/association.rb:86:in `scope' - activerecord (4.2.3) lib/active_record/associations/collection_association.rb:423:in `scope' - activerecord (4.2.3) lib/active_record/associations/collection_association.rb:435:in `get_records' - activerecord (4.2.3) lib/active_record/associations/collection_association.rb:455:in `find_target' - activerecord (4.2.3) lib/active_record/associations/collection_association.rb:392:in `load_target' - activerecord (4.2.3) lib/active_record/associations/has_many_association.rb:26:in `handle_dependency' - activerecord (4.2.3) lib/active_record/associations/builder/association.rb:146:in `block in add_destroy_callbacks' - activesupport (4.2.3) lib/active_support/callbacks.rb:446:in `block in make_lambda' - activesupport (4.2.3) lib/active_support/callbacks.rb:162:in `block in halting' - activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `block in call' - activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call' - activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks' - activerecord (4.2.3) lib/active_record/callbacks.rb:292:in `destroy' - activerecord (4.2.3) lib/active_record/transactions.rb:281:in `block in destroy' - activerecord (4.2.3) lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction' - activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction' - activerecord (4.2.3) lib/active_record/transactions.rb:348:in `with_transaction_returning_status' - activerecord (4.2.3) lib/active_record/transactions.rb:281:in `destroy' - app/controllers/users_controller.rb:47:in `set_saml' - actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action' - actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action' - actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action' - activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call' - activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile' - activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call' - activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks' - actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action' - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument' - activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument' - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument' - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action' - actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action' - activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action' - actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process' - actionview (4.2.3) lib/action_view/rendering.rb:30:in `process' - actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch' - actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch' - actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve' - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve' - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve' - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call' - omniauth (1.2.2) lib/omniauth/strategy.rb:404:in `call_app!' - omniauth (1.2.2) lib/omniauth/strategy.rb:262:in `mock_call!' - omniauth (1.2.2) lib/omniauth/strategy.rb:181:in `call!' - omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call' - warden (1.2.3) lib/warden/manager.rb:35:in `block in call' - warden (1.2.3) lib/warden/manager.rb:34:in `call' - rack (1.6.4) lib/rack/etag.rb:24:in `call' - rack (1.6.4) lib/rack/conditionalget.rb:25:in `call' - rack (1.6.4) lib/rack/head.rb:13:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call' - rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context' - rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call' - activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call' - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call' - active-fedora (9.4.2) lib/active_fedora/ldp_cache.rb:26:in `call' - activerecord (4.2.3) lib/active_record/migration.rb:377:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call' - activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks' - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call' - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call' - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call' - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call' - railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app' - railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call' - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged' - activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged' - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged' - railties (4.2.3) lib/rails/rack/logger.rb:20:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call' - rack (1.6.4) lib/rack/methodoverride.rb:22:in `call' - rack (1.6.4) lib/rack/runtime.rb:18:in `call' - activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call' - rack (1.6.4) lib/rack/lock.rb:17:in `call' - actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call' - rack (1.6.4) lib/rack/sendfile.rb:113:in `call' - railties (4.2.3) lib/rails/engine.rb:518:in `call' - railties (4.2.3) lib/rails/application.rb:165:in `call' - rack (1.6.4) lib/rack/urlmap.rb:66:in `block in call' - rack (1.6.4) lib/rack/urlmap.rb:50:in `call' - rack-test (0.6.3) lib/rack/mock_session.rb:30:in `request' - rack-test (0.6.3) lib/rack/test.rb:244:in `process_request' - rack-test (0.6.3) lib/rack/test.rb:58:in `get' - /usr/lib64/ruby/2.1.0/forwardable.rb:183:in `get' - capybara (2.5.0) lib/capybara/rack_test/browser.rb:60:in `process' - capybara (2.5.0) lib/capybara/rack_test/browser.rb:35:in `process_and_follow_redirects' - capybara (2.5.0) lib/capybara/rack_test/browser.rb:26:in `submit' - capybara (2.5.0) lib/capybara/rack_test/form.rb:76:in `submit' - capybara (2.5.0) lib/capybara/rack_test/node.rb:61:in `click' - capybara (2.5.0) lib/capybara/node/element.rb:134:in `block in click' - capybara (2.5.0) lib/capybara/node/base.rb:84:in `synchronize' - capybara (2.5.0) lib/capybara/node/element.rb:134:in `click' - capybara (2.5.0) lib/capybara/node/actions.rb:39:in `click_button' - capybara (2.5.0) lib/capybara/session.rb:698:in `block (2 levels) in ' - capybara (2.5.0) lib/capybara/dsl.rb:51:in `block (2 levels) in ' - spec/features/saml_spec.rb:105:in `block (5 levels) in ' - rspec-expectations (3.3.1) lib/rspec/matchers/built_in/raise_error.rb:49:in `matches?' - rspec-expectations (3.3.1) lib/rspec/matchers/built_in/raise_error.rb:67:in `does_not_match?' - rspec-expectations (3.3.1) lib/rspec/expectations/handler.rb:78:in `does_not_match?' - rspec-expectations (3.3.1) lib/rspec/expectations/handler.rb:72:in `block in handle_matcher' - rspec-expectations (3.3.1) lib/rspec/expectations/handler.rb:27:in `with_matcher' - rspec-expectations (3.3.1) lib/rspec/expectations/handler.rb:70:in `handle_matcher' - rspec-expectations (3.3.1) lib/rspec/expectations/expectation_target.rb:67:in `not_to' - rspec-expectations (3.3.1) lib/rspec/expectations/expectation_target.rb:92:in `not_to' - spec/features/saml_spec.rb:105:in `block (4 levels) in ' - rspec-core (3.3.2) lib/rspec/core/example.rb:206:in `block in run' - rspec-core (3.3.2) lib/rspec/core/example.rb:430:in `block in with_around_and_singleton_context_hooks' - rspec-core (3.3.2) lib/rspec/core/example.rb:388:in `block in with_around_example_hooks' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:478:in `block in run' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:618:in `block in run_around_example_hooks_for' - rspec-core (3.3.2) lib/rspec/core/example.rb:273:in `call' - rspec-rails (3.3.3) lib/rspec/rails/adapters.rb:127:in `block (2 levels) in ' - rspec-core (3.3.2) lib/rspec/core/example.rb:378:in `instance_exec' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:389:in `execute_with' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:620:in `block (2 levels) in run_around_example_hooks_for' - rspec-core (3.3.2) lib/rspec/core/example.rb:273:in `call' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:621:in `run_around_example_hooks_for' - rspec-core (3.3.2) lib/rspec/core/hooks.rb:478:in `run' - rspec-core (3.3.2) lib/rspec/core/example.rb:388:in `with_around_example_hooks' - rspec-core (3.3.2) lib/rspec/core/example.rb:430:in `with_around_and_singleton_context_hooks' - rspec-core (3.3.2) lib/rspec/core/example.rb:203:in `run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:559:in `block in run_examples' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:555:in `run_examples' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:521:in `run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `block in run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `block in run' - rspec-core (3.3.2) lib/rspec/core/example_group.rb:522:in `run' - rspec-core (3.3.2) lib/rspec/core/runner.rb:115:in `block (3 levels) in run_specs' - rspec-core (3.3.2) lib/rspec/core/runner.rb:115:in `block (2 levels) in run_specs' - rspec-core (3.3.2) lib/rspec/core/configuration.rb:1627:in `with_suite_hooks' - rspec-core (3.3.2) lib/rspec/core/runner.rb:114:in `block in run_specs' - rspec-core (3.3.2) lib/rspec/core/reporter.rb:77:in `report' - rspec-core (3.3.2) lib/rspec/core/runner.rb:113:in `run_specs' - rspec-core (3.3.2) lib/rspec/core/runner.rb:89:in `run' - rspec-core (3.3.2) lib/rspec/core/runner.rb:73:in `run' - rspec-core (3.3.2) lib/rspec/core/runner.rb:41:in `invoke' - rspec-core (3.3.2) exe/rspec:4:in `' - /usr/bin/rspec:23:in `'"
          # ./spec/features/saml_spec.rb:106:in `block (4 levels) in <top (required)>'

     6.2) Failure/Error: User.destroy_all
          ActiveRecord::StatementInvalid:
            Mysql2::Error: Table 'hydranorthdev.bookmarks' doesn't exist: SHOW FULL FIELDS FROM `bookmarks`
          # ./spec/features/saml_spec.rb:43:in `block (3 levels) in <top (required)>'

  7) SAML Users with existing legacy accounts who log in with their legacy credentials should be able to link to their CCID via the user edit form
     Failure/Error: User.destroy_all
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Table 'hydranorthdev.bookmarks' doesn't exist: SHOW FULL FIELDS FROM `bookmarks`
     # ./spec/features/saml_spec.rb:43:in `block (3 levels) in <top (required)>'

  8) SAML Users with existing legacy accounts who log in with their legacy credentials should not be prompted to confirm their email addresses when linking a CCID
     Failure/Error: User.destroy_all
     ActiveRecord::StatementInvalid:
       Mysql2::Error: Table 'hydranorthdev.bookmarks' doesn't exist: SHOW FULL FIELDS FROM `bookmarks`
     # ./spec/features/saml_spec.rb:43:in `block (3 levels) in <top (required)>'

  9) User ccid user should need to confirm adding a ccid
     Failure/Error: expect { subject.confirm_ccid! }.to change { ActionMailer::Base.deliveries.count }.by(1)
       expected result to have changed by 1, but was changed by 0
     # ./spec/models/user_spec.rb:69:in `block (3 levels) in <top (required)>'

**Comment by weiweishi** [comment]
Remaining issues are recorded on #686
