### PR TITLE
fixes the solr query to include generic files that belongs to communi…

### LINKED ISSUE #814: Dataverse Community not showing its members
Items from Dataverse are now associated with a community called Dataverse Datasets (cf. #781), but the landing page for that community does not list any items.

### PR DESCRIPTION
**Pull request by weiweishi**
…ty directly, fixes #814

### CODE REVIEW

File: app/models/search_builder.rb [hunk 1]
```diff
@@ -5,6 +5,6 @@ class SearchBuilder < Blacklight::SearchBuilder
 
    def include_collection_ids(solr_parameters)
     solr_parameters[:fq] ||= []
-    solr_parameters[:fq] << "(active_fedora_model_ssi:Collection AND belongsToCommunity_tesim:#{collection.id}) OR hasCollectionId_ssim:#{collection.id}"
+    solr_parameters[:fq] << "(-hasCollectionId_tesim:[* TO *] AND belongsToCommunity_tesim:#{collection.id}) OR hasCollectionId_ssim:#{collection.id}"
```
Comment (pbinkley) [inline app/models/search_builder.rb]: Could we fix the tesim fields and close #745 at the same time?

**Comment by weiweishi** [comment]
updated the PR according to @pbinkley's suggestion.

**Comment by pbinkley** [comment]
Note: adding ```:symbol``` is the first step to getting rid of some ```tesim``` fields that contain unparsable tokens. Once we do a full reindexing, we'll be able to remove references to the ```tesim``` versions of these fields.
